CavassinGomes/goservice

goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Administrador.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Agendamento.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Cliente.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Prestador.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Servico.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Usuario.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/enums/Perfil.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/enums/StatusAgendamento.java

Iniciando a configuração de usuários

---

goserviceapp/src/main/java/com/soulcode/goserviceapp/controller/AuthControler.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/controller/HomeController.java
goserviceapp/src/main/resources/templates/cadastroCliente.html
goserviceapp/src/main/resources/templates/fragments/header.html
goserviceapp/src/main/resources/templates/fragments/layout.html
goserviceapp/src/main/resources/templates/home.html
goserviceapp/src/main/resources/templates/login.html

Construção do cabeçalho da  página e fragmentos

---

goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Agendamento.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Cliente.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Prestador.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Servico.java
goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Usuario.java

Implementação dos relacionamentos de agendamento

---

goserviceapp/src/main/java/com/soulcode/goserviceapp/domain/Agendamento.java

Arrumando bug de relação entre tabelas

---

goserviceapp/src/main/java/com/soulcode/goserviceapp/controller/AuthControler.java
goserviceapp/src/main/resources/templates/cadastroCliente.html
goserviceapp/src/main/resources/templates/fragments/layout.html
goserviceapp/src/main/resources/templates/login.html

Construção e mapeamento da página Cadastro e Login

---

mysql/POPULATE.sql

Populando as tabelas usuario, servicos, e prestadores_servicos.

---

src/main/resources/templates/home.html

Carrossel de publicitário

---

src/main/java/com/soulcode/goserviceapp/controller/ClienteController.java
src/main/java/com/soulcode/goserviceapp/domain/Agendamento.java
src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
src/main/java/com/soulcode/goserviceapp/service/exceptions/DataInvalidaException.java
src/main/resources/static/js/script.js
src/main/resources/templates/agendarServico.html

feat: Verificacao da data de agendamento

---

src/main/java/com/soulcode/goserviceapp/controller/PrestadorController.java
src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
src/main/resources/templates/agendaPrestador.html

feat: Criando filtro de busca de agendamentos do prestador por data.

---

src/main/resources/templates/agendaPrestador.html
src/main/resources/templates/agendarServico.html
src/main/resources/templates/dadosCliente.html
src/main/resources/templates/dadosPrestador.html
src/main/resources/templates/dashboard.html
src/main/resources/templates/editarServico.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/layout.html
src/main/resources/templates/historicoCliente.html
src/main/resources/templates/home.html
src/main/resources/templates/servicosAdmin.html
src/main/resources/templates/usuariosAdmin.html

Arrumando o rodapé, criação do footer.html dentro do fragments.

fix:Correcao e criacao do footer dentro do fragments

---

src/main/java/com/soulcode/goserviceapp/controller/HomeController.java
src/main/resources/static/css/main.css
src/main/resources/templates/politicaTermos.html

Feat: Implementação da página termos e condições e pólitica de privacidade

---

src/main/java/com/soulcode/goserviceapp/controller/ClienteController.java
src/main/java/com/soulcode/goserviceapp/controller/PrestadorController.java
src/main/java/com/soulcode/goserviceapp/domain/Chat.java
src/main/java/com/soulcode/goserviceapp/repository/ChatRepository.java
src/main/java/com/soulcode/goserviceapp/service/ChatService.java
src/main/resources/static/css/main.css
src/main/resources/static/js/script.js
src/main/resources/templates/agendaPrestador.html
src/main/resources/templates/chatCliente.html
src/main/resources/templates/chatPrestador.html
src/main/resources/templates/historicoCliente.html

Feat: Sistema de comunicação simples entre o Cliente e o Prestador.

---

src/main/java/com/soulcode/goserviceapp/domain/Cliente.java
src/main/java/com/soulcode/goserviceapp/domain/Endereco.java
src/main/java/com/soulcode/goserviceapp/domain/Prestador.java

Feat: cliente e prestador podem adicionar endereço

---

src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java

Foi criado um query que busca os números de serviços agendados agrupados por status.

feat:Consulta que busca os numeros de serviços agendados por status

---

src/main/java/com/soulcode/goserviceapp/repository/AgendamentoRepository.java
src/main/java/com/soulcode/goserviceapp/service/AgendamentoService.java
src/main/java/com/soulcode/goserviceapp/service/exceptions/ConflitoHorarioException.java

tratamento do conflito de horário

---

src/main/resources/templates/historicoCliente.html

Feat: Criação do modal com informações do prestador na página de historicoCliente

---

src/main/resources/templates/historicoCliente.html

Fix: Ajustes no modal de informações dos prestadores ná página histoicoCliente.

---

src/main/resources/templates/agendaPrestador.html

Feat: Adicionando modal de informações do cliente na tabela de agendamentos do prestador.

---

src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java

Otimizando a busca de usuarios usando o cacheamento.

feat:Cacheamento para otimizar a busca de dados de usuarios

---

src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
src/main/java/com/soulcode/goserviceapp/repository/UsuarioRepository.java
src/main/java/com/soulcode/goserviceapp/service/UsuarioService.java
src/main/resources/templates/usuariosAdmin.html

Criação do filtro de busca de usurio na página administrativa.

feat:Filtro de busca na pagina administrativa

---

src/main/java/com/soulcode/goserviceapp/controller/AdministradorController.java
src/main/java/com/soulcode/goserviceapp/repository/ServicoRepository.java
src/main/java/com/soulcode/goserviceapp/service/ServicoService.java
src/main/resources/application.properties
src/main/resources/templates/servicosAdmin.html

Criação de um filtro de busca  de serviços na pagina administrativa.

feat:Filtro de busca de servico na pagina administrativa

---

src/main/resources/templates/home.html

Feat: Cards publicitários na home.
